services:
  traefik:
    image: traefik:v3.0
    container_name: mini_crm_traefik
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
    networks:
      - mini_crm_net

  postgres:
    image: postgres:17-alpine
    container_name: mini_crm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mini_crm_leads}
      POSTGRES_USER: ${POSTGRES_USER:-arthur}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-3326}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - mini_crm_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-arthur} -d ${POSTGRES_DB:-mini_crm_leads}",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s
    networks:
      - mini_crm_net

  pgadmin:
    image: dpage/pgadmin4:9.5
    container_name: mini_crm_pgadmin
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@mini-crm.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123456}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_LOGIN_BANNER: "'Mini CRM de Leads'"
    ports:
      - "8081:80"
    volumes:
      - mini_crm_pgadmin_data:/var/lib/pgadmin
    networks:
      - mini_crm_net

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: mini_crm_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://${POSTGRES_USER:-arthur}:${POSTGRES_PASSWORD:-3326}@postgres:5432/${POSTGRES_DB:-mini_crm_leads}?schema=public
      JWT_SECRET: ${JWT_SECRET:-desenvolvimento-mini-crm-altere-esta-chave-antes-da-producao}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      COOKIE_SECURE: ${COOKIE_SECURE:-false}
      COOKIE_SAME_SITE: ${COOKIE_SAME_SITE:-strict}
      RATE_LIMIT_E2E_BYPASS_ENABLED: ${RATE_LIMIT_E2E_BYPASS_ENABLED:-false}
      RATE_LIMIT_E2E_BYPASS_KEY: ${E2E_TEST_KEY:-}
    networks:
      - mini_crm_net

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost/api/v1}
    container_name: mini_crm_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NODE_ENV: production
    networks:
      - mini_crm_net

networks:
  mini_crm_net:
    driver: bridge

volumes:
  mini_crm_postgres_data:
  mini_crm_pgadmin_data:
